### ISSUE TITLE
Data[i,j] with a ResultSet type makes a copy of Data?

### ISSUE THREAD

**Issue by songroom** [quinnj/SQLite.jl#64]
i want to know whether Data[i,j] with a ResultSet type makes a copy of Data,  the way is same as Array?
thank you!

**Comment by quinnj** [comment]
You're correct that currently doing `Data[i,j]` on a `ResultSet` makes a copy, largely due to waiting on https://github.com/JuliaLang/julia/pull/9150. It wouldn't be a huge change to use ArrayViews, but I'm also not personally interested in it because 1) we can just wait until it's the default behavior in Base, most likely before the official release of 0.4 and 2) users can use ArrayViews themselves on the `ResultSet` without too much hassle. If you'd like to put together a PR, I wouldn't mind merging, but it's not high priority for me personally.

**Comment by songroom** [comment]
thank you very much!
